# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 04:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_positive', models.BooleanField(help_text='Whether or not this is a positive comment.', verbose_name='Is positive?')),
                ('time', models.TimeField(auto_now_add=True, help_text='The time when the comment was written.')),
            ],
            options={
                'verbose_name_plural': 'Comments',
                'verbose_name': 'Comment',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of theme.', max_length=50, verbose_name='Title')),
            ],
            options={
                'verbose_name_plural': 'Themes',
                'verbose_name': 'Theme',
            },
        ),
        migrations.CreateModel(
            name='Thumb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_positive', models.BooleanField(help_text='Whether or not this is a positive thumb.', verbose_name='Is positive?')),
                ('time', models.TimeField(auto_now_add=True, help_text='The time when the thumbs up or down was given.')),
            ],
            options={
                'verbose_name_plural': 'Thumbs',
                'verbose_name': 'Thumb',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of video.', max_length=50, verbose_name='Title')),
                ('date_uploaded', models.DateField(help_text='The date it was uploaded. (Make sure that videos that are more than 1 year old should not be added, as they are less relevant.', verbose_name='Date')),
                ('views', models.FloatField(help_text='The amount of views the video received.', verbose_name='Views')),
                ('themes', models.ManyToManyField(to='core.Theme', verbose_name='Themes.')),
            ],
            options={
                'verbose_name_plural': 'Videos',
                'verbose_name': 'Video',
            },
        ),
        migrations.AddField(
            model_name='thumb',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Video', verbose_name='The video referenced by this thumb.'),
        ),
        migrations.AddField(
            model_name='comment',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Video', verbose_name='The video referenced by this comment.'),
        ),
    ]
